name: shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  google_sign_in: ^5.3.0
  firebase_auth: ^3.3.16
  flutter_signin_button: ^2.0.0
  cloud_firestore: ^3.1.14
  firebase_core: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/google_logo.png
    - assets/anonymous_icon.png
    # TODO: Add slanted menu asset (104)
    - assets/images/